import "@/styles/globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { GlobalLoading } from "@/components/global";
import { GeniusModal } from "@/components/modal";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BookingApp clone",
  description: "Generated by BookingApp clone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          {children}
          <GeniusModal />
          <ToastContainer />
          <GlobalLoading />
        </MantineProvider>
      </body>
    </html>
  );
}
